# Generated by Django 5.2 on 2025-04-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
