# Generated by Django 5.2 on 2025-04-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0004_alter_shift_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
