# Generated by Django 3.2.15 on 2025-04-17 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0005_alter_shift_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 4, 17, 18, 17, 4, 390748)),
            preserve_default=False,
        ),
    ]
