# Generated by Django 5.2 on 2025-04-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0006_auto_20250417_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.shift')),
            ],
        ),
    ]
