# Generated by Django 5.2 on 2025-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0007_break'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telegram_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
