# Generated by Django 3.2.15 on 2025-05-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0008_alter_employee_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekend',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='weekend',
            name='start_date',
        ),
    ]
